name: EC2 cloud server

on:
  push:
    branches:
      - nikhil

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3 

      - name: setup the node 
        uses: actions/setup-node@v3
        with: 
          node-version: '23.11.0'
        
      - name: Install dependencies 
        run: npm install --legacy-peer-devs

      - name: Deploy to EC2 
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_EC2_HOST }}
          username: ${{ secrets.STAGING_EC2_USER }}
          key: ${{ secrets.STAGING_EC2_SSH_KEY }}
          script: |
            echo "ğŸ Starting SSH deploy..."
            cd /home/ubuntu/mern || { echo "âŒ /mern folder missing"; exit 1; }
            pwd
            cd /home/ubuntu/mern/ui || { echo "âŒ /ui folder missing"; exit 1; }
            pwd
            git config --global credential.helper store
            echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
            git pull origin staging || { echo "âŒ git pull failed"; exit 1; }
            echo "âœ… Deployment script finished."






