name: EC2 cloud server

on:
  push:
    branches:
      - staging

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3 

      - name: setup the node 
        uses: actions/setup-node@v3
        with: 
          node-version: '23.11.0'
        
      - name: Install dependencies 
        run: npm install --legacy-peer-devs

      - name: Deploy to EC2 
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_EC2_HOST }}
          username: ${{ secrets.STAGING_EC2_USER }}
          key: ${{ secrets.STAGING_EC2_SSH_KEY }}
          script: |
            echo "ğŸ Starting SSH deploy..."
            cd /home/ubuntu/mern/ui
            git config --global credential.helper store
            echo "https://nikhil8052:${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials
            
            git_output=$(git pull origin staging)
            echo "$git_output"
            
            if echo "$git_output" | grep -q 'Already up to date.'; then
              echo "ğŸš€ No changes, skipping npm install and pm2 restart."
            else
              echo "ğŸ”„ Changes detected, running npm install, build, and pm2 restart."
              npm run build
              pm2 restart dropship-ui-3000
            fi

            echo "âœ… Deployment script finished."






